### ISSUE TITLE
SPDX available?

### ISSUE THREAD

**Issue by robinagandhi** [yevster/App-BOM-ination#1]
Thanks for putting this together. A few observations:
1. Github is detecting only the project level asserted license information and correctly reporting it as Apache 2.0. 
2. Do you have a sample “ideal” SPDX document developed for this project? If yes, it would be great if you can include this in the top level project directory itself or link it from the readme. 
3. Collecting SPDX documents for this project produced by different tools will be interesting. Do you plan to do this?

**Comment by yevster** [comment]
1. Github can only be expected to "know" the project-level license. But this being a nightmare scenario, there's nothing stopping a bad committer from committing a file from his proprietary work project under an evil proprietary license (Which is what InsufficientKarmaException.java simulates).
2. I have a partial one which I built using [SPDX-Edit](http://github.com/yevster/spdx-edit), but that tool doesn't yet support snippets, which would be required to provide a complete file. 
3. The answer is yes. There are plans in the works to do a "bake-off" as part of LinuxCon Europe. I believe those plans will be mailed out to the SPDX tech team list as soon as Kate and the conference organizers finalize them.

**Comment by yevster** [comment]
@robinagandhi, the bake-off [has been announced](https://spdx.org/news/news/2016/09/spdx-plugfest-linuxcon-europe-6-october-2016).

As part of this bake-off, we'll hopefully see a healthy range of SPDX documents of this project.

FYI, I'll also be [doing a presentation](https://linuxconcontainerconeurope2016.sched.org/event/7oA5/documenting-your-software-supply-chain-with-linked-data-yev-bronshteyn-black-duck-software) right before the bake-off about working with SPDX as linked data (so things like how to examine SPDX with sparql queries, etc), using this project as the sample material.

I'll be closing this issue, but if you have any other questions or comments, you're always welcome to email me directly.
